# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [1]:
item_a = 2.0 + 3.0 / 5.0 == 10
item_b = (item_a + 10.2) - 5.0 * 2.0 <= 2.9
item_c = 10 <= item_a / item_b + 33.8 < 100
item_d = 5 != item_a / (item_b + item_c)
item_e = 33 == item_d * 2

print (item_a)
print (item_b)
print (item_c)
print (item_d)
print (item_e)

False
True
True
True
False

## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [2]:
ex_2_a = ('a',1,True,'b',0,False) == ('a',True,1,'b',False,0)
ex_2_b = ['a',1,True,'b',0,False] == ('a',True,1,'b',False,0)
ex_2_c = ['a',1,True,'b',0,False] == ['a',True,1,'b',False,0]
ex_2_d = ['a',1,True,'b',0,False] < ['a',True,1]
ex_2_e = ['a',1,True,'b',0,False] != 1
ex_2_f = ['a',True,1] > ['a',True,1] >= ['a',1,True,'b',0,False]

print(ex_2_a, ex_2_b, ex_2_c, ex_2_d, ex_2_e, ex_2_f)

True False True False True False

## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [22]:
import pandas as pd

df_atv7 = pd.read_csv("./df_atv7.csv", index_col= "Unnamed: 0").round(3)
df_atv7

             1      2       3      4  Médias
0        2.600  2.800  34.729  0.069  10.050
1        0.139  1.612   1.673  5.893   2.329
2        0.263  0.372   2.600  2.800   1.509
3       34.729  0.069   0.139  1.612   9.137
4        1.673  5.893   0.263  0.372   2.050
Médias   7.881  2.149   7.881  2.149   5.015

## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [4]:
import numpy as np

array_4 = np.ones(df_atv7.shape, dtype=int)
array_4

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [9]:
comp = (df_atv7.values == array_4)
quant = np.sum(comp)

print (f"Total de itens com valores iguais: {quant}")

Total de itens com valores iguais: 0

## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [10]:
comp_2 = (df_atv7.values > array_4)
quant_2 = np.sum(comp_2)

print (f"Total de itens com valores superiores: {quant_2}")

Total de itens com valores superiores: 22

## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [11]:
comp_3 = (df_atv7 <= array_4)
quant_3 = np.sum(comp_3)

print (f"Total de itens iguais ou inferiores: {quant_3}")

Total de itens iguais ou inferiores: 8

## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [28]:
comp_4 = (df_atv7 > 0) & (df_atv7 < 1)
quant_4 = comp_4.values.sum()

print(f"{quant_4} valores da DataFrame estão entre 0 e 1")

8 valores da DataFrame estão entre 0 e 1

## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [30]:
comp_5 = (df_atv7.iloc[:, -1] <= 5)
quant_5 = comp_5.values.sum()

print(f"{quant_5} valores das médias das linhas são inferiores ou iguais à 5")
df_atv7

3 valores das médias das linhas são inferiores ou iguais à 5

             1      2       3      4  Médias
0        2.600  2.800  34.729  0.069  10.050
1        0.139  1.612   1.673  5.893   2.329
2        0.263  0.372   2.600  2.800   1.509
3       34.729  0.069   0.139  1.612   9.137
4        1.673  5.893   0.263  0.372   2.050
Médias   7.881  2.149   7.881  2.149   5.015

## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [31]:
comp_6 = (df_atv7.iloc[-1, :] > 5)
quant_6 = comp_6.values.sum()

print(f"{quant_6} valores das médias das colunas são superiiores à 5")
df_atv7

3 valores das médias das colunas são superiiores à 5

             1      2       3      4  Médias
0        2.600  2.800  34.729  0.069  10.050
1        0.139  1.612   1.673  5.893   2.329
2        0.263  0.372   2.600  2.800   1.509
3       34.729  0.069   0.139  1.612   9.137
4        1.673  5.893   0.263  0.372   2.050
Médias   7.881  2.149   7.881  2.149   5.015